### ISSUE TITLE
EXISTS subqueries doesn't seem to be supported

### ISSUE THREAD

**Issue by fredsensibill** [thatdot/quine#45]
**Describe the bug**
Quine's [Cypher documentation](https://quine.io/reference/cypher/) don't have any mention of not supporting EXISTS subqueries in standing queries outputs. But still it seems that Quine is not able to compile them.

**To Reproduce**
Using quine 1.9.0, add this standing query to any recipe:
```yaml
standingQueries:
  - pattern:
      type: Cypher
      query: |-
        MATCH (n)
        RETURN DISTINCT id(n) as id
    outputs:
      exists-subquery:
        type: CypherQuery
        query: |-
          MATCH (n)
          WHERE id(n) = $that.data.id
            AND EXISTS {
              MATCH (n)-->(m)
            }
          RETURN id(n)
```

You'll get the following exception:

> Exception in thread "main" com.thatdot.quine.graph.cypher.CypherException$Compile: Unsupported expression @ Some(Position(3,7,44,SourceText(MATCH (n)
WHERE id(n) = $that.data.id
  AND EXISTS {
    MATCH (n)-->(m)
  }
RETURN id(n))))

**Expected behavior**
Either EXISTS subqueries should be supported or the documentation needs to updated with this limitation, possibly providing some workarounds.
